import "./globals.css";

export const metadata = {
  title: "One App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" font-inter">{children}</body>
    </html>
  );
}
